//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public string CPF { get; set; }
        public string Numero { get; set; }
        public string Descricao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
